# Generated by Django 3.2.7 on 2022-07-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JPK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_walidacji_jpk', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik_walidujacy', models.CharField(max_length=24)),
            ],
        ),
    ]
