# Generated by Django 3.2.7 on 2022-07-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walidator_vat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jpk',
            name='plik_zaladowany_przez_uzytkownika',
            field=models.FileField(default='', upload_to='documents'),
            preserve_default=False,
        ),
    ]
