# Generated by Django 3.2.7 on 2022-07-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walidator_vat', '0002_jpk_plik_zaladowany_przez_uzytkownika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jpk',
            name='plik_zaladowany_przez_uzytkownika',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
